interfaces:
  - name: GigabitEthernet0/0
    description: ""
  - name: GigabitEthernet0/1
    description: ""
  - name: GigabitEthernet0/2
    description: ""
  ip_address: "192.168.31.231
  subnet_mask: "24
  - name: GigabitEthernet0/3
    description: ""
  - name: Loopback0
    description: "Managed by Ansible"
  ip_address: "2.2.2.2
  subnet_mask: "32
